version: '3.8'

services:
  sublicup-db:
    container_name: sublicup-db
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - sublicup-db-volume:/var/lib/mysql

volumes:
  sublicup-db-volume:
