version: '3.9'

services:
  sublicup-db:
    container_name: sublicup-db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sublicup
    volumes:
      - sublicup-db-volume:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  sublicup-db-volume:
